spring.application.name=be

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banking_6ttn}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8081
server.servlet.context-path=/api
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:23130334@st.hcmuaf.edu.vn}
spring.mail.password=${MAIL_PASSWORD:zplu doha yvyl kzgp}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
